version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '80:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://34.29.174.102:3002
      - NODE_ENV=production
    restart: always

  backend:
    build: ./backend
    ports:
      - '3002:3002'
    environment:
      - DB_HOST=34.56.143.55
      - DB_PORT=5432
      - DB_NAME=gps_trucks_japan
      - DB_USER=postgres
      - DB_PASSWORD=Megumi12
      - NODE_ENV=production
    restart: always