name: Deploy to GCP Cloud Run

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-northeast1
  BACKEND_SERVICE: gps-backend
  FRONTEND_SERVICE: gps-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push Backend
      run: |
        docker build -t gcr.io/$PROJECT_ID/$BACKEND_SERVICE:$GITHUB_SHA ./backend
        docker push gcr.io/$PROJECT_ID/$BACKEND_SERVICE:$GITHUB_SHA

    - name: Build and Push Frontend
      run: |
        docker build -t gcr.io/$PROJECT_ID/$FRONTEND_SERVICE:$GITHUB_SHA ./frontend
        docker push gcr.io/$PROJECT_ID/$FRONTEND_SERVICE:$GITHUB_SHA

    - name: Deploy Backend to Cloud Run
      run: |
        gcloud run deploy $BACKEND_SERVICE \
          --image gcr.io/$PROJECT_ID/$BACKEND_SERVICE:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --port 3002 \
          --add-cloudsql-instances ${{ secrets.CLOUD_SQL_CONNECTION }} \
          --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }},NODE_ENV=production"

    - name: Deploy Frontend to Cloud Run
      run: |
        BACKEND_URL=$(gcloud run services describe $BACKEND_SERVICE --region $REGION --format 'value(status.url)')
        gcloud run deploy $FRONTEND_SERVICE \
          --image gcr.io/$PROJECT_ID/$FRONTEND_SERVICE:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --port 3000 \
          --set-env-vars "NEXT_PUBLIC_API_URL=$BACKEND_URL,NODE_ENV=production"

    - name: Get Service URLs
      run: |
        echo "Backend URL: $(gcloud run services describe $BACKEND_SERVICE --region $REGION --format 'value(status.url)')"
        echo "Frontend URL: $(gcloud run services describe $FRONTEND_SERVICE --region $REGION --format 'value(status.url)')"